portshaker: Improve poudriere support.

diff --git a/portshaker.subr.in b/portshaker.subr.in
--- a/portshaker.subr.in
+++ b/portshaker.subr.in
@@ -59,14 +59,6 @@ case $use_zfs in
 	;;
 esac
 
-_use_poudriere=0
-use_poudriere=${use_poudriere:=0}
-case $use_poudriere in
-[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
-	_use_poudriere=1
-	;;
-esac
-
 #
 #	functions
 #	---------
@@ -358,7 +350,7 @@ run_portshaker_command()
 		# Proceed with the command
 		case "${_portshaker_arg}" in
 		clone_to|copy_to)
-			_args=`getopt apt:z: ${_portshaker_extra_args}`
+			_args=`getopt aP:pt:z: ${_portshaker_extra_args}`
 			if [ $? -ne 0 ]; then
 				portshaker_usage
 			fi
@@ -369,6 +361,9 @@ run_portshaker_command()
 				case "${_i}" in
 					-p)
 						_pretend=1
+						shift ;;
+					-P)
+						_poudriere_tree="$2"; shift
 						shift ;;
 					-t)
 						_target="$2"; shift
@@ -419,6 +414,17 @@ run_portshaker_command()
 				fi # _use_zfs -eq 1
 				if [ $_use_zfs -eq 1 ]; then
 					if [ -d "${_target}/.zfs" ]; then
+						if [ -n "${_poudriere_tree}" -a -d "${_target}/ports/.zfs" ]; then
+							debug "Running 'zfs destroy ${_target_dataset}/ports'."
+							if [ $_pretend -eq 0 ]; then
+								zfs destroy "${_target_dataset}/ports"
+								if [ $? -ne 0 ]; then
+									echo "The following processes are using '${_target}/ports':"
+									fstat -f "${_target}/ports"
+									err 1 "Can't destroy ZFS filesystem '${_target_dataset}'."
+								fi
+							fi
+						fi
 						debug "Running 'zfs destroy ${_target_dataset}'."
 						if [ $_pretend -eq 0 ]; then
 							zfs destroy ${_target_dataset}
@@ -428,6 +434,15 @@ run_portshaker_command()
 								err 1 "Can't destroy ZFS filesystem '${_target_dataset}'."
 							fi
 						fi
+					fi
+					if [ -n "${_poudriere_tree}" ]; then
+						# d
+						debug "Running 'zfs create ${_target_dataset}'."
+						if [ $_pretend -eq 0 ]; then
+							zfs create -o "poudriere:type=ports" -o "poudriere:name=${_poudriere_tree}" -o "mountpoint=${_target}" "${_target_dataset}"
+						fi
+						_target="${_target}/ports"
+						_target_dataset="${_target_dataset}/ports"
 					fi
 					# Get the latests snapshot available.
 					_snapshot=`cd ${_portsdir}/.zfs/snapshot && ls -d portshaker-* | tail -n 1`
@@ -441,13 +456,6 @@ run_portshaker_command()
 					debug "Running 'zfs set mountpoint="${_target}" "${_target_dataset}"'."
 					if [ $_pretend -eq 0 ]; then
 						zfs set mountpoint="${_target}" "${_target_dataset}" || err 1 "Can't set '${_target_dataset}' mountpoint to '${_target}'."
-					fi
-					if [ $_use_poudriere -eq 1 ]; then
-						debug "Running 'zfs set poudriere:type=ports poudriere:name=$(basename ${_target_dataset}) ${_target_dataset}'"
-						if [ $_pretend -eq 0 ]; then
-							zfs set poudriere:type="ports" "${_target_dataset}" || err 1 "Can't set poudriere metadata on '${_target_dataset}'."
-							zfs set poudriere:name="$(basename ${_target_dataset})" "${_target_dataset}" || err 1 "Can't set poudriere metadata on '${_target_dataset}'."
-						fi
 					fi
 				else
 					debug "Running 'rsync ${RSYNC_FLAGS} ${RSYNC_ARGS} ${RSYNC_EXCLUDE} \"${_portsdir}/\" \"${_target}\"'."
