Add ZFS support to speed up cloning with use_zfs.

diff --git a/portshaker.subr.in b/portshaker.subr.in
--- a/portshaker.subr.in
+++ b/portshaker.subr.in
@@ -399,11 +399,40 @@ run_portshaker_command()
 			case "${_portshaker_arg}" in
 			clone_to)
 				info "Cloning '${_portsdir}' to '${_target}'."
+				case "${use_zfs}" in
+				[yY][eE][sS]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
+					_source_dataset=`zfs list -H | awk "\\\$5 == \"${_portsdir}\" {print \\\$1}"`
+					_target_parent=`dirname ${_target}`
+					_target_parent_dataset=`zfs list -H | awk "\\\$5 == \"${_target_parent}\" {print \\\$1}"`
+					_target_dataset="${_target_parent_dataset}/`basename ${_target}`"
+					if [ -z "${_source_dataset}" -o -z "${_target_parent_dataset}" ]; then
+						warn "'${_portsdir}' and '${_target_parent}' shall be ZFS volumes when \$use_zfs=yes. Falling back to rsync(1)."
+						use_zfs="no"
+					fi
+				esac
+				case "${use_zfs}" in
+				[yY][eE][sS]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
+					if [ -d "${_target}/.zfs" ]; then
+						debug "Running 'zfs destroy ${_target_dataset}'."
+						zfs destroy ${_target_dataset} || err 1 "Can't destroy ZFS volume '${_target_dataset}'."
+					fi
+					if [ -d "${_portsdir}/.zfs/snapshot/portshaker" ]; then
+						debug "Running 'zfs destroy ${_source_dataset}@portshaker'."
+						zfs destroy ${_source_dataset}@portshaker || err 1 "Can't destroy ZFS snapshot '${_source_dataset}@portshaker'."
+					fi
+					debug "Running 'zfs snapshot ${_source_dataset}@portshaker'."
+					zfs snapshot ${_source_dataset}@portshaker || err 1 "Can't create ZFS snapshot '${_source_dataset}@portshaker'."
+					debug "Running 'zfs clone ${_source_dataset}@portshaker ${_target_dataset}'."
+					zfs clone ${_source_dataset}@portshaker ${_target_dataset} || err 1 "Can't clone '${_source_dataset}@portshaker' to '${_target_dataset}'."
+					;;
+				*)
 				debug "Running '${RSYNC} ${RSYNC_ARGS} ${RSYNC_EXCLUDE} \"${_portsdir}/\" \"${_target}\"'."
 				${RSYNC} ${RSYNC_ARGS} ${RSYNC_EXCLUDE} "${_portsdir}/" "${_target}"
 				if [ $? -ne 0 ]; then
 					err 1 "Failed to clone '${_portsdir}' to '${_target}'."
 				fi
+					;;
+				esac
 				;;
 			copy_to)
 				info "Copying '${_portsdir}' to '${_target}'."
