poudriere: Add a way to automatically set poudriere's metadata on ZFS filesystems.

diff --git a/portshaker.subr.in b/portshaker.subr.in
--- a/portshaker.subr.in
+++ b/portshaker.subr.in
@@ -59,6 +59,14 @@ case $use_zfs in
 	;;
 esac
 
+_use_poudriere=0
+use_poudriere=${use_poudriere:=0}
+case $use_poudriere in
+[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
+	_use_poudriere=1
+	;;
+esac
+
 #
 #	functions
 #	---------
@@ -443,6 +451,13 @@ run_portshaker_command()
 					debug "Running 'zfs set mountpoint="${_target}" "${_target_dataset}"'."
 					if [ $_pretend -eq 0 ]; then
 						zfs set mountpoint="${_target}" "${_target_dataset}" || err 1 "Can't set '${_target_dataset}' mountpoint to '${_target}'."
+					fi
+					if [ $_use_poudriere -eq 1 ]; then
+						debug "Running 'zfs set poudriere:type=ports poudriere:name=$(basename ${_target_dataset}) ${_target_dataset}'"
+						if [ $_pretend -eq 0 ]; then
+							zfs set poudriere:type="ports" "${_target_dataset}" || err 1 "Can't set poudriere metadata on '${_target_dataset}'."
+							zfs set poudriere:name="$(basename ${_target_dataset})" "${_target_dataset}" || err 1 "Can't set poudriere metadata on '${_target_dataset}'."
+						fi
 					fi
 				else
 					debug "Running 'rsync ${RSYNC_FLAGS} ${RSYNC_ARGS} ${RSYNC_EXCLUDE} \"${_portsdir}/\" \"${_target}\"'."
