Fix initial creation of portshap'ed source ports trees.
"portsnap alfred" is equivalent to "portsnap cron/fetch" && "portsnap update"
so we need to "portsnap extract" at some point, and therefore "portsnap fetch"
manually before.

Reported by:	nagyt@hu.inter.net, nh.techn@gmail.com

diff --git a/portshaker.subr.in b/portshaker.subr.in
--- a/portshaker.subr.in
+++ b/portshaker.subr.in
@@ -913,10 +913,24 @@ run_portshaker_command()
 				;;
 			portsnap)
 				PORTSNAP_FLAGS="${PORTSNAP_FLAGS} -p ${_portsdir}"
+				if [ ! -f "${_portsdir}/.portsnap.INDEX" ]; then
+					# "portsnap alfred" <=> "portsnap fetch && portsnap update", but we need to "portsnap extract" here.
+					debug "Running 'portsnap ${PORTSNAP_FLAGS} fetch'."
+					portsnap ${PORTSNAP_FLAGS} fetch
+					if [ $? -ne 0 ]; then
+						err 1 "portsnap fetch failed."
+					fi
+					debug "Running 'portsnap ${PORTSNAP_FLAGS} extract'."
+					portsnap ${PORTSNAP_FLAGS} extract
+					if [ $? -ne 0 ]; then
+						err 1 "portsnap extract failed."
+					fi
+				else
 				debug "Running 'portsnap ${PORTSNAP_FLAGS} alfred'."
 				portsnap ${PORTSNAP_FLAGS} alfred
 				if [ $? -ne 0 ]; then
 					err 1 "portsnap alfred failed."
+				fi
 				fi
 				;;
 			rsync)
